In [ ]:
What is NumPy?
-- NumPy (Numerical Python) is a powerful library used for:
- Fast mathematical calculations
- Working with arrays (faster than lists)
- Data science, AI, ML, etc.

In [1]:
#Import:
import numpy as np

In [ ]:
#Why NumPy?
✔ Faster than Python lists
✔ Uses less memory
✔ Supports vectorized operations
✔ Useful for matrices & scientific computing

In [2]:
#-- NumPy Array --

In [3]:
#1. Creating Array


import numpy as np

arr = np.array([1, 2, 3, 4])
print(arr)

[1 2 3 4]


In [4]:
#2. Multi-Dimensional Array

arr2 = np.array([[1, 2], [3, 4]])
print(arr2)

[[1 2]
 [3 4]]


In [5]:
#3. Check Dimensions

print(arr.ndim)   # dimension
print(arr.shape)  # size

1
(4,)


In [6]:
#--Special Arrays

np.zeros((2,3))   # all 0
np.ones((2,3))    # all 1
np.eye(3)         # identity matrix
np.arange(0,10,2) # range
np.linspace(0,1,5) # equal parts

array([0.  , 0.25, 0.5 , 0.75, 1.  ])