In [2]:
!pip install numpy


In [3]:
import numpy as np


In [5]:
print(np.__version__)

2.4.1


In [ ]:
NumPy (short for Numerical Python) is a powerful Python library used for working with numbers, especially large datasets and mathematical operations.

In [ ]:
What is NumPy?
-- NumPy is a library that provides support for:
- Fast numerical calculations
- Multi-dimensional arrays (like lists but more powerful)
- Mathematical functions (mean, sum, matrix operations, etc.)

In [ ]:
Why use NumPy?
- Faster than Python lists
- Used in data science, machine learning, AI
- Handles large data efficiently
- Supports vector & matrix operations

In [ ]:
#Array Fundamentals:-- NumPy (Numerical Python) is the backbone of data science and machine learning in Python. At its core is the ndarray (n-dimensional array), which is much faster and more memory-efficient than standard Python lists.

In [ ]:
Topics: 
-- 1D, 2D, 3D arrays 
-- Shape & size: 
-- arr.shape 
-- arr.ndim 
-- arr.size Data types (dtype)

In [ ]:

#-- 1. 1D, 2D, 3D Arrays

In [1]:
#1D Array (like a list)
import numpy as np

a = np.array([1, 2, 3, 4])
print(a)

[1 2 3 4]


In [2]:
#2D Array (like a table / matrix)

b = np.array([[1, 2, 3],
              [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [4]:
#3D Array (stack of tables)

c = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])
print(c)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [5]:
#-- 2. Array Properties/2 rows, 3 columns


#1.shape -- Shows structure (rows, columns)

print(b.shape)

(2, 3)


In [6]:
#2.ndim -- Number of dimensions

print(c.ndim)

3


In [7]:
#3.size -- Total number of elements

print(b.size)

6


In [8]:
#4. dtype -- Data type of elements/(system dependent)

d = np.array([1, 2, 3])
print(d.dtype)

int64


In [ ]:
#Final Understanding
-- Every NumPy array has:

- Shape → structure
- Dimensions → depth
- Size → total values
- Data type → type of values

In [ ]:
#Memory Trick
1D = Line
2D = Table
3D = Stack

In [9]:
#Quick Practice
import numpy as np

arr = np.array([[10, 20], [30, 40]])

print(arr.shape)   # ?
print(arr.ndim)    # ?
print(arr.size)    # ?
print(arr.dtype)   # ?

(2, 2)
2
4
int64


In [ ]:
#-- EXAMPLES --

In [10]:
#1. 1D Array Example

import numpy as np

arr1 = np.array([10, 20, 30, 40])

print("Array:", arr1)
print("Shape:", arr1.shape)
print("Dimensions:", arr1.ndim)
print("Size:", arr1.size)
print("Data Type:", arr1.dtype)

Array: [10 20 30 40]
Shape: (4,)
Dimensions: 1
Size: 4
Data Type: int64


In [11]:
#2. 2D Array Example
arr2 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print("Array:\n", arr2)
print("Shape:", arr2.shape)
print("Dimensions:", arr2.ndim)
print("Size:", arr2.size)

Array:
 [[1 2 3]
 [4 5 6]]
Shape: (2, 3)
Dimensions: 2
Size: 6


In [12]:
#3. 3D Array Example

arr3 = np.array([
    [[1, 2], [3, 4]],
    [[5, 6], [7, 8]]
])

print("Dimensions:", arr3.ndim)
print("Shape:", arr3.shape)
print("Size:", arr3.size)

Dimensions: 3
Shape: (2, 2, 2)
Size: 8


In [13]:
#4. Data Type Example
arr = np.array([1, 2, 3])
print(arr.dtype)

arr_float = np.array([1, 2, 3], dtype=float)
print(arr_float.dtype)

int64
float64


In [14]:
#5. Mixed Data Example

arr = np.array([1, 2.5, 3])
print(arr)
print(arr.dtype)

[1.  2.5 3. ]
float64


In [16]:
#6. Real-Life Example (Student Marks)

marks = np.array([[85, 90, 88],
                  [78, 82, 80]])

print("Shape:", marks.shape)
print("Total Students:", marks.shape[0])
print("Subjects:", marks.shape[1])

Shape: (2, 3)
Total Students: 2
Subjects: 3


In [ ]:
3. Indexing & Slicing in NumPy
-- Indexing and slicing are used to access specific elements or subsets of arrays.

In [17]:
# 1. Indexing (Access Single Element)
# -- Used to get one element from an array.
# -- Example (1D Array)


import numpy as np

arr = np.array([10, 20, 30, 40, 50])

print(arr[0])   # First element → 10
print(arr[2])   # Third element → 30
print(arr[-1])  # Last element → 50

10
30
50


In [18]:
# Example (2D Array)

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr[0, 1])  # Row 0, Column 1 → 2
print(arr[1, 2])  # Row 1, Column 2 → 6

2
6


In [ ]:
2. Slicing (Access Multiple Elements)
-- Used to get a range of elements

-- Syntax:
arr[start : end : step]


start → where to begin
end → where to stop (NOT included)
step → skip elements

In [19]:
# Example (1D Array)


arr = np.array([10, 20, 30, 40, 50])

print(arr[1:4])    # [20 30 40]
print(arr[:3])     # [10 20 30]
print(arr[::2])    # [10 30 50]

[20 30 40]
[10 20 30]
[10 30 50]


In [20]:
#Example (2D Array)

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Slice rows and columns
print(arr[0:2, 1:3])

# Explanation:

# Rows: 0 to 1
# Columns: 1 to 2

[[2 3]
 [5 6]]


In [21]:
#Quick Practice
arr = np.array([5, 10, 15, 20, 25])

# Try yourself:
print(arr[1])      # ?
print(arr[1:4])    # ?
print(arr[::-1])   # ?

10
[10 15 20]
[25 20 15 10  5]


In [ ]:
#4. Array Operations in NumPy

Array operations are powerful because NumPy performs them element-wise and very fast (no loops needed 🚀).

In [22]:
#1. Arithmetic Operations

# -- Perform math directly on arrays
# -- Example

import numpy as np

a = np.array([10, 20, 30])
b = np.array([1, 2, 3])

print(a + b)   # [11 22 33]
print(a - b)   # [9 18 27]
print(a * b)   # [10 40 90]
print(a / b)   # [10. 10. 10.]

[11 22 33]
[ 9 18 27]
[10 40 90]
[10. 10. 10.]


In [23]:
#2. Scalar Operations

# -- Apply operation with a single number
# -- Example

a = np.array([10, 20, 30])

print(a + 5)   # [15 25 35]
print(a * 2)   # [20 40 60]

[15 25 35]
[20 40 60]


In [24]:
 #3. Universal Functions (ufuncs)

# -- Built-in fast functions
# -- Example


import numpy as np

a = np.array([4, 9, 16])

print(np.sqrt(a))   # [2. 3. 4.]
print(np.log(a))    # log values
print(np.sin(a))    # sine values

[2. 3. 4.]
[1.38629436 2.19722458 2.77258872]
[-0.7568025   0.41211849 -0.28790332]


In [25]:
#4. Aggregation Functions

# -- Used to get summary values
# -- Example

a = np.array([10, 20, 30, 40])

print(np.sum(a))    # 100
print(np.mean(a))   # 25.0
print(np.max(a))    # 40
print(np.min(a))    # 10

100
25.0
40
10


In [26]:
#5. Operations on 2D Arrays

# -- Works row-wise & column-wise
# -- Example


a = np.array([[1, 2],
              [3, 4]])

print(np.sum(a))         # Total → 10
print(np.sum(a, axis=0)) # Column-wise → [4 6]
print(np.sum(a, axis=1)) # Row-wise → [3 7]

10
[4 6]
[3 7]


In [27]:
#6. Broadcasting

# -- Allows operations on different-shaped arrays
# -- Example

a = np.array([1, 2, 3])
b = 2

print(a * b)   # [2 4 6]

[2 4 6]


In [30]:
#With 2D:

a = np.array([[1, 2, 3],
              [4, 5, 6]])

b = np.array([2, 2, 2])

print(a * b)

[[ 2  4  6]
 [ 8 10 12]]


In [ ]:
#-- 5. Mathematical Functions

Mathematical functions in NumPy allow you to perform fast calculations on entire arrays (element-wise ⚡).

In [31]:
#1. Basic Mathematical Functions
# Example

import numpy as np

a = np.array([4, 9, 16, 25])

print(np.sqrt(a))   # Square root → [2. 3. 4. 5.]
print(np.square(a)) # Square → [16 81 256 625]
print(np.abs(a))    # Absolute value

[2. 3. 4. 5.]
[ 16  81 256 625]
[ 4  9 16 25]


In [33]:
#2. Trigonometric Functions

# -- Works in radians
# -- Example

a = np.array([0, np.pi/2, np.pi])

print(np.sin(a))   # [0, 1, 0]
print(np.cos(a))   # [1, 0, -1]
print(np.tan(a))   # tan values

[0.0000000e+00 1.0000000e+00 1.2246468e-16]
[ 1.000000e+00  6.123234e-17 -1.000000e+00]
[ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [35]:
#3. Logarithmic & Exponential Functions
#-- Example

a = np.array([1, 2, 3])

print(np.log(a))     # Natural log (ln)
print(np.log10(a))   # Base-10 log
print(np.exp(a))     # e^x

[0.         0.69314718 1.09861229]
[0.         0.30103    0.47712125]
[ 2.71828183  7.3890561  20.08553692]


In [36]:
#4. Rounding Functions
#-- Example

a = np.array([1.2, 2.5, 3.7])

print(np.round(a))   # [1. 2. 4.]
print(np.floor(a))   # [1. 2. 3.]
print(np.ceil(a))    # [2. 3. 4.]

[1. 2. 4.]
[1. 2. 3.]
[2. 3. 4.]


In [37]:
#5. Statistical Functions
#-- Example

a = np.array([10, 20, 30, 40])

print(np.mean(a))   # 25.0
print(np.median(a)) # 25.0
print(np.std(a))    # Standard deviation
print(np.var(a))    # Variance

25.0
25.0
11.180339887498949
125.0


In [38]:
#6. Min, Max & Sum
#-- Example

a = np.array([5, 10, 15])

print(np.min(a))   # 5
print(np.max(a))   # 15
print(np.sum(a))   # 30

5
15
30


In [ ]:
#-- Mathematical Functions in NumPy




Function	Full Form / Meaning              	Description
sqrt()	    Square Root	                        Returns √x
abs()	    Absolute Value	                    Removes negative sign
sin()	    Sine	                            Trigonometric sine (radians)
cos()	    Cosine	                            Trigonometric cosine
tan()	    Tangent           	                Trigonometric tangent
log()	    Logarithm (Natural Log)	            Base e (ln)
log10()	    Log Base 10	                        Common logarithm
exp()	    Exponential	                        e^x
round()	    Round Off	                        Nearest integer
floor()	    Floor Value	                        Lower integer
ceil()	    Ceiling Value	                    Upper integer
mean()	    Arithmetic Mean	                    Average value
median()	Median	                            Middle value
std()	    Standard Deviation	                Spread of data
var()	    Variance	                        Square of std

In [ ]:
#6. Reshaping & Manipulation in NumPy
-- This topic is 🔥 very important for data preprocessing, ML, and interviews

In [44]:
#1. reshape()

# -- Change the shape of an array (without changing data)
# -- Example

import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6])

print(arr.reshape(2, 3))

[[1 2 3]
 [4 5 6]]


In [46]:
#2. flatten()
#-- Convert multi-dimensional array → 1D copy

arr = np.array([[1, 2], [3, 4]])

print(arr.flatten())

[1 2 3 4]


In [47]:
#3. ravel()

#-- Similar to flatten but returns view (faster)

print(arr.ravel())

[1 2 3 4]


In [48]:
#4. transpose()
#-- Swap rows ↔ columns

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr.T)

[[1 4]
 [2 5]
 [3 6]]


In [49]:
#5. resize()
#-- Change shape (can modify original array)

arr = np.array([1, 2, 3, 4])
arr.resize(2, 2)

print(arr)

[[1 2]
 [3 4]]


In [50]:
#6. concatenate()
#-- Join arrays

a = np.array([1, 2])
b = np.array([3, 4])

print(np.concatenate((a, b)))

[1 2 3 4]


In [51]:
#7. stack()
#-- Join arrays along a new axis

a = np.array([1, 2])
b = np.array([3, 4])

print(np.stack((a, b)))

[[1 2]
 [3 4]]


In [53]:
#8. split()
#-- Split array into parts

arr = np.array([1, 2, 3, 4])

print(np.split(arr, 4))

[array([1]), array([2]), array([3]), array([4])]


In [ ]:
#Key Difference (Important)
Function	Type
reshape	    Change shape
flatten	    Copy to 1D
ravel	    View to 1D
transpose	Swap axes
concatenate	Join arrays
split	    Break arrays

In [ ]:
#-- 7. Linear Algebra in NumPy (Important 🔥)

Linear Algebra is the core of Machine Learning, AI, and Data Science 💯
It deals with vectors, matrices, and operations on them.

In [54]:
#1. Matrix Representation
#-- Arrays = Matrices in NumPy

import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

In [55]:
#2. Matrix Addition & Subtraction
print(A + B)
print(A - B)

[[ 6  8]
 [10 12]]
[[-4 -4]
 [-4 -4]]


In [56]:
#3. Matrix Multiplication
#-- Important 🔥 (used in ML models)

print(np.dot(A, B))

[[19 22]
 [43 50]]


In [58]:
#4. Transpose of Matrix
#-- Swap rows ↔ columns

print(A.T)
print(B.T)

[[1 3]
 [2 4]]
[[5 7]
 [6 8]]


In [59]:
#5. Determinant
#-- Helps check if matrix is invertible

print(np.linalg.det(A))

-2.0000000000000004


In [60]:
#6. Inverse of Matrix
#-- Used to solve equations

print(np.linalg.inv(A))

[[-2.   1. ]
 [ 1.5 -0.5]]


In [61]:
#7. Eigenvalues & Eigenvectors
#-- Very important in ML & AI

values, vectors = np.linalg.eig(A)

print(values)
print(vectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


In [62]:
#8. Solving Linear Equations
#-- Solve AX = B

A = np.array([[2, 1],
              [1, 3]])

B = np.array([8, 13])

X = np.linalg.solve(A, B)
print(X)

[2.2 3.6]


In [ ]:
#-- 8. Random Module in NumPy 🎲

The Random module (np.random) is used to generate random numbers and arrays
👉 Very useful in ML, testing, simulations, and data science

In [63]:
#1. Random Number (0 to 1)
import numpy as np

print(np.random.rand())

0.7190079829721254


In [64]:
#2. Random Array
print(np.random.rand(2, 3))

[[0.06379333 0.6177399  0.53853282]
 [0.24551656 0.87024524 0.9170203 ]]


In [66]:
#3. Random Integers
print(np.random.randint(1, 5))

4


In [67]:
print(np.random.randint(1, 10, (2, 3)))

[[4 6 4]
 [7 1 2]]


In [68]:
#4. Random Choice
arr = [10, 20, 30, 40]

print(np.random.choice(arr))

40


In [69]:
#5. Shuffle
arr = np.array([1, 2, 3, 4])

np.random.shuffle(arr)
print(arr)

[3 1 4 2]


In [70]:
#6. Normal Distribution
print(np.random.randn(3))

[-0.61901231  0.81355215 -0.09674606]


In [71]:
#7. Seed (Important 🔥)
#-- Makes output repeatable

np.random.seed(42)

print(np.random.rand(3))

[0.37454012 0.95071431 0.73199394]


In [ ]:
#Easy Summary
Function	Use
rand()	    0–1 random
randint()	integers
choice()	pick random
shuffle()	mix data
randn() 	normal distribution
seed()	    fix randomness

In [ ]:
Final Learning Path (Simple View)
Basics
Arrays
Indexing
Operations
Functions
Reshaping
Linear Algebra
Random
Projects